<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>scanner-api</AssemblyName>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <Version>1.0.4.0</Version>
    <FileVersion>1.0.4.0</FileVersion>
    <AssemblyVersion>1.0.4.0</AssemblyVersion>
    <Authors>Isrg Rajan</Authors>
    <Company>RatioJuris</Company>
    <Product>Universal Scanner API Integration Service by RatioJuris</Product>
    <Description>Proprietary zero-dependency middleware engine mapping WIA, TWAIN, and eSCL capabilities natively.</Description>
    <Copyright>Copyright 2026 RatioJuris. All Rights Reserved.</Copyright>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
</Project>
